### ISSUE TITLE
Send group messages

### ISSUE THREAD

**Issue by rubdos** [Michael-F-Bryan/libsignal-service-rs#24]

**Comment by gferon** [comment]
@rubdos you mentioned that it worked when you tested, right?

**Comment by rubdos** [comment]
Yes indeed. The Java version supposes that it is handled by the client application, so that's how I have implemented it too. `service` does not have any knowledge of group members. This can be closed, I think!

**Comment by rubdos** [comment]
Reopening because #38 will internalize sync messages, which means group messages cannot be handled at the application side anymore.

**Comment by gferon** [comment]
So in the end, #38 is not really internalizing sending group messages, since it just checks for `group` and `group_v2` inside of the `DataMessage`, which still has to be properly set by the client.

**Comment by rubdos** [comment]
We might want to think about a clean API later maybe. But having it partially internal is already quite nice, if it simplifies the application side, what do you think?
