### ISSUE TITLE
delete_all_sessions on EndSession

### ISSUE THREAD

**Issue by rubdos** [Michael-F-Bryan/libsignal-service-rs#30]
When an EndSession is received, the receiver needs to forget all session state. In the Java library, the `delete_all_sessions` method is called by the implementor (i.e., the Android app). Currently, this is implemented exactly like that, but it might be useful to consider implementing this here already.

**Comment by rubdos** [comment]
I just bounced on this again, since Whisperfish does the deletion itself currently, but is only capable enough to delete e164-based sessions (and not the new UUID ones). Makes it a bit more important to me than it was before.

**Comment by gferon** [comment]
I'll have a look later, I think it should be easy to implement.
