### ISSUE TITLE
Unable to get authorized with a non-default device ID after linking

### ISSUE THREAD

**Issue by matej-g** [Michael-F-Bryan/libsignal-service-rs#68]
First of all, nice project! I've been poking around to use it for my own Signal CLI utility.

However, I have been unable to get authorized with the push service after linking a device and instantiating a new push service with appropriately set service config and credentials (i.e. all requests end up with `401 Unauthorized`).

After some more investigation (and after looking at the forked [libsignal-service-java](https://github.com/Turasa/libsignal-service-java/blob/bdd1c753d67a2552d24865dee94c55e5148d55b2/service/src/main/java/org/whispersystems/signalservice/internal/push/PushServiceSocket.java#L1871)), I came to understand that the authorization header should also include the device ID, in case the request is being made on behalf of non-primary device. I.e. for non-primary device, the header should be composed in format `{identifier}.{device_id}:{password}`.

Locally, I was able to make the authorization work by building the login with the said device ID. 

I was wondering whether this is the right solution to my problem (or whether I'm doing something incorrectly from the beginning). If so, I'd be also happy to provide a PR for this.

**Comment by rubdos** [comment]
Hi! Thanks for reporting!  I'm mainly using the library as primary device, while Gabriel uses it for secondary devices. I think either it should be like you say, or I think you could add a `device_id` to the `Credentials`. If you do that, do feel free to break the public interface; you probably noticed we do that on a regular basis ;-)

@gferon, how do you handle this? I suppose you pass the login with the dot?

**Comment by matej-g** [comment]
> or I think you could add a `device_id` to the `Credentials`.

Just to complete the information, this is how I'm doing it locally (added `device_id` and adjusted the `login` method).

**Comment by rubdos** [comment]
Feel free to make a pull request and assign Gabriel as reviewer. He's been quite busy the last few weeks, but I think that's gonna be the cleanest solution indeed :-)

**Comment by matej-g** [comment]
Will do, thanks!
